export interface GeneMetric {
  percentage: number;
  label: string;
  disclaimer: string;
  comedyNote: string;
}

export function calculateGeneCompatibility(cciScore: number): GeneMetric {
  return {
    percentage: cciScore,
    label: "SIMULATED COCKROACH GENE COMPATIBILITY™",
    disclaimer: "IMPORTANT DISCLAIMER: This percentage does NOT represent DNA, genetics, biological ancestry, physical mutation, or actual cockroach genomic sequencing. It is an intentionally absurd computational entertainment metric generated by the Department of Unnecessary Biology.",
    comedyNote: "The department would like to stress that no geneticists were harmed during this calculation, though several expressed severe professional concern."
  };
}
